#!/bin/sh -f

# execute w/sudo

# Package list from "Raspberry Pi Computer Vision Programming"
# by Ashwin Pajankar
# http://www.amazon.com/gp/product/1784398284
apt-get install -y libopencv-dev
apt-get install -y build-essential
apt-get install -y libavformat-dev
apt-get install -y x264
apt-get install -y v4l-utils
apt-get install -y ffmpeg
apt-get install -y libcv2.3
apt-get install -y libcvaux2.3
apt-get install -y libhighgui2.3
apt-get install -y opencv-doc
apt-get install -y libcv-dev
apt-get install -y libcvaux-dev
apt-get install -y libhighgui-dev
apt-get install -y python-numpy
apt-get install -y python-scipy
apt-get install -y python-matplotlib
apt-get install -y python-pandas
apt-get install -y python-nose
apt-get install -y libgtkglext1-dev
apt-get install -y libpng12-0
apt-get install -y libpng12-dev
apt-get install -y libpng++-dev
apt-get install -y libpng3
apt-get install -y libpnglite-dev
apt-get install -y zlib1g-dbg
apt-get install -y zlib1g
apt-get install -y zlib1g-dev
apt-get install -y pngtools
apt-get install -y libtiff4-dev
apt-get install -y libtiff4
apt-get install -y libtiffxx0c2
apt-get install -y libtiff-tools
apt-get install -y libjpeg8
apt-get install -y libjpeg8-dev
apt-get install -y libjpeg8-dbg
apt-get install -y libavcodec-dev
apt-get install -y libavcodec53
apt-get install -y libavformat53
apt-get install -y libgstreamer0.10-0-dbg
apt-get install -y libgstreamer0.10-0
apt-get install -y libgstreamer0.10-dev
apt-get install -y libxine1-ffmpeg
apt-get install -y libxine1-bin
apt-get install -y libunicap2
apt-get install -y libunicap2-dev
apt-get install -y libdc1394-22-dev
apt-get install -y libdc1394-22
apt-get install -y libdc1394-utils
apt-get install -y libv4l-0
apt-get install -y libv4l-dev
apt-get install -y libpython2.6
apt-get install -y python-dev
apt-get install -y python2.6-dev
apt-get install -y libgtk2.0-dev
apt-get install -y libswscale-dev
apt-get install -y libjpeg-dev
apt-get install -y libwebp-dev
apt-get install -y libpng-dev
apt-get install -y libtiff5-dev
apt-get install -y libjasper-dev
apt-get install -y libopenexr-dev
apt-get install -y libgdal-dev
apt-get install -y python-tk
apt-get install -y python3-dev
apt-get install -y python3-tk
apt-get install -y python3-numpy
apt-get install -y libeigen3-dev
apt-get install -y python-opencv
apt-get install -y libpngwriter0-dev
apt-get install -y libpngwriter0c2
